# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/clean-nbdev',
                'doc_host': 'https://anasbraj.github.io',
                'git_url': 'https://github.com/anasbraj/clean-nbdev',
                'lib_path': 'clean_nbdev'},
  'syms': {'clean_nbdev.core': {'clean_nbdev.core.foo': ('core.html#foo', 'clean_nbdev/core.py')}}}
